Создадим в ручную дата фрейм

In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame({'2020': [100, 50, 80, 1000, 1900, 120, 250],
                   '2023': [150, 75, 150, 1800, 3000, 200, 300]}, index=['Билет на массовое катание для взрослых','Льготный билет на массовое катание',
'Прокат коньков', 'Абонемент на 1 месяц без проката коньков', 
'Абонемент на 1 месяц с прокатом коньков', 'Заточка коньков', 'Разогрев 1 пары фигурных и хоккейных ботинок в термопечи'])
df

                                                    2020  2023
Билет на массовое катание для взрослых               100   150
Льготный билет на массовое катание                    50    75
Прокат коньков                                        80   150
Абонемент на 1 месяц без проката коньков            1000  1800
Абонемент на 1 месяц с прокатом коньков             1900  3000
Заточка коньков                                      120   200
Разогрев 1 пары фигурных и хоккейных ботинок в ...   250   300

In [13]:
df['Абсолютное изменение'] = pd.Series(df['2023'] - df['2020'])
df

,2020,2023,Абсолютное изменение
Билет на массовое катание для взрослых,100,150,50
Льготный билет на массовое катание,50,75,25
Прокат коньков,80,150,70
Абонемент на 1 месяц без проката коньков,1000,1800,800
Абонемент на 1 месяц с прокатом коньков,1900,3000,1100
Заточка коньков,120,200,80
Разогрев 1 пары фигурных и хоккейных ботинок в термопечи,250,300,50

In [14]:
df['Темп роста, %'] = np.round((df['2023'] / df['2020']) * 100, 2)
df

,2020,2023,Абсолютное изменение,"Темп роста, %"
Билет на массовое катание для взрослых,100,150,50,150.00
Льготный билет на массовое катание,50,75,25,150.00
Прокат коньков,80,150,70,187.50
Абонемент на 1 месяц без проката коньков,1000,1800,800,180.00
Абонемент на 1 месяц с прокатом коньков,1900,3000,1100,157.89
Заточка коньков,120,200,80,166.67
Разогрев 1 пары фигурных и хоккейных ботинок в термопечи,250,300,50,120.00